POST  http://localhost:3000/sign-up
Content-Type: application/json

{
  "email": "alex.dev@example.com",
  "userName": "AlexDev99",
  "password": "SuperSecurePassword123!",
  "major": "Computer Science"
}
###
POST  http://localhost:3000/sign-in
Content-Type: application/json

{
  "email": "alex.dev@example.com",
  "password": "SuperSecurePassword123!"
}

###
POST http://localhost:3000/add-Task
Content-Type:application/json

{
  "task_name": "Finish backend API integration",
  "category": "Development",
  "task_type": "Coding",
  "description": "Connect the add_task route to the MySQL database and test the JWT auth middleware.",
  "reminder_time": "2026-06-25 15:30:00"
}
###
GET http://localhost:3000/searh?searchType=category&searchValue=work
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoyLCJlbWFpbCI6ImVzbWFpbDEyM0BnbWFpbC5jb20iLCJpYXQiOjE3ODIxNzUzNTUsImV4cCI6MTc4MjE3NjI1NX0.3OwBBjFoKtmWMcIryp0xy1Horl4D-kG9MERAqWNt1z4
